name = "VolumeRegistration"
uuid = "fc41fb7d-15c6-4320-bc68-d176a63a31d9"
authors = ["Vilim <vilim@neuro.mpg.de> and contributors"]
version = "0.1.1"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PaddedBlocks = "00ed6140-19f5-4745-8680-fdb6f4f73d16"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractFFTs = "0.5"
CoordinateTransformations = "0.5"
CuArrays = "2.2"
DocStringExtensions = "0.8"
FFTW = "1.2"
ImageTransformations = "0.8"
Interpolations = "0.12"
JuliennedArrays = "0.2"
PaddedBlocks = "0.1"
StaticArrays = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
